filter:
    excluded_paths:
        - 'dist/*'
        - 'docs/*'
checks:
    javascript: true
build:
    nodes:
        analysis:
            environment:
                node:
                    version: 6.0.0
